name: Download Cache
description: Download and restore the Cache artifact (check ../upload-cache)
inputs:
  artifactName:
    description: Name of the artifact on which the cache is published
    default: cache-dir
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ${{ inputs.artifactName }}
        path: '.'
    - run: unzip -q -n ${{ inputs.artifactName }}.zip
      shell: bash
    - run: rm -f ${{ inputs.artifactName }}.zip
      shell: bash
