import {
  ApiConfiguration
} from './api-configuration';
import {
  BuilderConfiguration
} from './builder-configuration';

export interface BuilderApiConfiguration extends ApiConfiguration, BuilderConfiguration {

}

/**
 * Configuration of the generate script.
 * For the full example, see generate.config.json in the examples folder
 */
export interface ApisConfiguration {

  /**
   * The list of API configuration that will be generated by the script
   */
  apis: BuilderApiConfiguration[];
}
