changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: 'Breaking Changes :warning:'
      labels:
        - 'breaking change'
    - title: 'Fixes :bug:'
      labels:
        - bug
    - title: 'Documentation :file_cabinet:'
      labels:
        - documentation
    - title: 'New Features :rocket:'
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
