import {
  bootstrapApplication,
} from '@angular/platform-browser';
import {
  App,
} from './app-devtools/app';

// eslint-disable-next-line no-console -- Generated by Angular
bootstrapApplication(App).catch((err) => console.error(err));
