import {
  bootstrapApplication
} from '@angular/platform-browser';
import {
  AppComponent
} from './app-devtools/app.component';

// eslint-disable-next-line unicorn/prefer-top-level-await, no-console -- Generated by Angular
bootstrapApplication(AppComponent).catch((err) => console.error(err));
