compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

packageExtensions:
  # TODO: Could be removed once https://github.com/actions/toolkit/issues/1684 is fixed
  "@actions/github@^6.0.0":
    dependencies:
      undici: ^5.25.4
  "@storybook/manager-api@*":
    dependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  eslint@*:
    dependencies:
      "@types/json-schema": "^7.0.15"
      "@eslint/core": "^0.6.0"
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^4.19.5

yarnPath: .yarn/releases/yarn-4.5.1.cjs
