compressionLevel: mixed

enableScripts: false

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@design-factory/design-factory@*":
    peerDependencies:
      "@angular/router": ~17.0.4
  "@nx/angular@^18.0.0":
    dependencies:
      "@angular-devkit/build-angular": ~17.0.3
      "@angular-devkit/core": ~17.0.3
      "@angular-devkit/schematics": ~17.0.3
      "@angular/compiler": ~17.0.4
      "@angular/compiler-cli": ~17.0.4
      "@schematics/angular": ~17.0.3
      "@types/node": ^20.0.0
      esbuild: ~0.20.0
      eslint: ^8.42.0
      nx: ~18.0.2
      rxjs: ^7.8.1
      typescript: ~5.2.2
  "@nx/cypress@^18.0.0":
    dependencies:
      typescript: ~5.2.2
  "@nx/devkit@^18.0.0":
    dependencies:
      nx: ~18.0.2
      typescript: ~5.2.2
  "@nx/eslint-plugin@^18.0.0":
    dependencies:
      "@typescript-eslint/parser": ^6.11.0
      eslint: ^8.42.0
  "@nx/eslint@^18.0.0":
    dependencies:
      nx: ~18.0.2
  "@nx/jest@^18.0.0":
    dependencies:
      nx: ~18.0.2
      typescript: ~5.2.2
  "@nx/js@^18.0.0":
    dependencies:
      "@types/node": ^20.0.0
      nx: ~18.0.2
      typescript: ~5.2.2
  "@nx/webpack@^18.0.0":
    dependencies:
      "@types/node": ^20.0.0
      nx: ~18.0.2
      typescript: ~5.2.2
  postcss-loader@^7.2.4:
    dependencies:
      "@types/node": ^20.0.0
  probot@*:
    dependencies:
      body-parser: ^1.20.2
      bottleneck: ^2.19.5

yarnPath: .yarn/releases/yarn-4.1.0.cjs
