compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

# Only accept packages published more than 3 days ago
# https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - '@agnos-ui/*'
  - '@amadeus-it-group/*'
  - '@design-factory/*'
  - 'tar@7.5.7'
  - '@modelcontextprotocol/sdk@1.26.0'
  - '@isaacs/brace-expansion@5.0.1'

packageExtensions:
  "@crxjs/vite-plugin@*":
    dependencies:
      "vite": ~7.3.1
      "type-fest": ^5.3.1
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": ^8.15.0
  "ngx-markdown@*":
    peerDependenciesMeta:
      "zone.js":
        "optional": true
  nx@*:
    dependencies:
      "@swc/core": ~1.15.3
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0
      "ioredis": ^5.3.2

yarnPath: .yarn/releases/yarn-4.12.0.cjs
