compressionLevel: mixed

enableScripts: false

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@design-factory/design-factory@*":
    dependencies:
      "@ng-select/ng-select": "~12.0.7"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
