nodeLinker: node-modules

packageExtensions:
  "@nguniversal/builders@^15.0.0":
    dependencies:
      "@angular/core": ~15.0.4
      "@angular/common": ~15.0.4
      typescript: ~4.8.4
      zone.js: ^0.12.0
  # "@angular-eslint/schematics@^15.1.0":
  #   dependencies:
  #     eslint: ^8.22.0
  #     typescript: ~4.8.4
  "@nrwl/angular@^15.0.0":
    dependencies:
      "@types/node": ^17.0.23
      "@angular-devkit/build-angular": ~15.0.4
      "@angular/compiler": ~15.0.4
      "@angular/compiler-cli": ~15.0.4
      nx: ^15.0.0
      typescript: ~4.8.4
  "@nrwl/cypress@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.8.4
  "@nrwl/devkit@^15.0.0":
    dependencies:
      typescript: ~4.8.4
  "@nrwl/jest@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.8.4
  "@nrwl/js@^15.0.0":
    dependencies:
      nx: ^15.0.0
  "@nrwl/linter@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.8.4
  "@nrwl/webpack@^15.0.0":
    dependencies:
      "@babel/core": ^7.17.9
      "@types/node": ^17.0.23
      nx: ^15.0.0
      typescript: ~4.8.4
  "@storybook/core-common@^6.5.9":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "@storybook/docs-tools@^6.5.9":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "@storybook/mdx1-csf@0.0.1":
    dependencies:
      "@babel/core": ^7.17.9

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
