compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

packageExtensions:
  "@design-factory/design-factory@*":
    dependencies:
      "@ng-select/ng-select": ~12.0.7
  "@storybook/manager-api@*":
    dependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"

yarnPath: .yarn/releases/yarn-4.4.0.cjs
