compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

packageExtensions:
  # TODO: Could be removed once https://github.com/actions/toolkit/issues/1684 is fixed
  "@actions/github@^6.0.0":
    dependencies:
      undici: ^5.25.4
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@typescript-eslint/rule-tester@*":
    dependencies:
      "@typescript-eslint/parser": ~8.22.0
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": ^8.15.0
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0

yarnPath: .yarn/releases/yarn-4.6.0.cjs
