compressionLevel: mixed

enableScripts: false

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@design-factory/design-factory@*":
    dependencies:
      "@ng-select/ng-select": "~12.0.7"
  "@nx/angular@^18.0.0":
    dependencies:
      "@angular-devkit/build-angular": ~17.3.0
      "@angular-devkit/core": ~17.3.0
      "@angular-devkit/schematics": ~17.3.0
      "@angular/compiler": ~17.3.0
      "@angular/compiler-cli": ~17.3.0
      "@schematics/angular": ~17.3.0
      "@types/node": ^20.0.0
      esbuild: ~0.20.0
      eslint: ^8.57.0
      nx: ~18.0.8
      rxjs: ^7.8.1
      typescript: ~5.4.2
  "@nx/cypress@^18.0.0":
    dependencies:
      typescript: ~5.4.2
  "@nx/devkit@^18.0.0":
    dependencies:
      nx: ~18.0.8
      typescript: ~5.4.2
  "@nx/eslint-plugin@^18.0.0":
    dependencies:
      "@typescript-eslint/parser": ^7.2.0
      eslint: ^8.57.0
  "@nx/eslint@^18.0.0":
    dependencies:
      nx: ~18.0.8
  "@nx/jest@^18.0.0":
    dependencies:
      nx: ~18.0.8
      typescript: ~5.4.2
  "@nx/js@^18.0.0":
    dependencies:
      "@types/node": ^20.0.0
      nx: ~18.0.8
      typescript: ~5.4.2
  "@nx/webpack@^18.0.0":
    dependencies:
      "@types/node": ^20.0.0
      nx: ~18.0.8
      typescript: ~5.4.2
  "jsonc-eslint-parser@*":
    dependencies:
      "@types/eslint": "^8.42.0"
      "@types/estree": "^1.0.5"
  "yaml-eslint-parser@*":
    dependencies:
      "@types/eslint": "^8.42.0"
  probot@*:
    dependencies:
      body-parser: ^1.20.2
      bottleneck: ^2.19.5

yarnPath: .yarn/releases/yarn-4.1.1.cjs
