approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@agnos-ui/*"
  - "@amadeus-it-group/*"
  - "@design-factory/*"

packageExtensions:
  "@crxjs/vite-plugin@*":
    dependencies:
      type-fest: ^5.3.1
  ngx-markdown@*:
    peerDependenciesMeta:
      zone.js:
        optional: true
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0
      ioredis: ^5.3.2

yarnPath: .yarn/releases/yarn-4.17.0.cjs
