compressionLevel: mixed

enableScripts: false

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@storybook/manager-api@*":
    dependencies:
      react: ^18.0.0
      react-dom: ^18.0.0
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: ~5.4.2
  "@design-factory/design-factory@*":
    dependencies:
      "@ng-select/ng-select": "~12.0.7"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
