compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

packageExtensions:
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": ^8.15.0
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0

yarnPath: .yarn/releases/yarn-4.9.2.cjs
