compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

packageExtensions:
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": ^8.15.0
  nx@*:
    dependencies:
      "@swc/core": ~1.12.0
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0
      "ioredis": ^5.3.2

yarnPath: .yarn/releases/yarn-4.9.4.cjs
