nodeLinker: pnp

packageExtensions:
  "jest-preset-angular@^12.2.3":
    dependencies:
      jest-util: ^28.1.3
  "@nrwl/angular@^15.0.0":
    dependencies:
      "@angular-devkit/build-angular": ~15.1.3
      "@angular/compiler": ~15.1.2
      "@angular/compiler-cli": ~15.1.2
      "@types/node": ^17.0.23
      nx: ^15.0.0
      typescript: ~4.9.4
  "@nrwl/cypress@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.9.4
  "@nrwl/devkit@^15.0.0":
    dependencies:
      typescript: ~4.9.4
  "@nrwl/jest@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.9.4
  "@nrwl/js@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.9.4
  "@nrwl/linter@^15.0.0":
    dependencies:
      nx: ^15.0.0
      typescript: ~4.9.4
  "@nrwl/webpack@^15.0.0":
    dependencies:
      "@babel/core": ^7.17.9
      "@types/node": ^17.0.23
      nx: ^15.0.0
      typescript: ~4.9.4
  "@storybook/core-common@^6.5.9":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "@storybook/docs-tools@^6.5.9":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "@storybook/mdx1-csf@0.0.1":
    dependencies:
      "@babel/core": ^7.17.9

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
