compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

# Only accept packages published more than 3 days ago
# https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - '@agnos-ui/*'
  - '@amadeus-it-group/*'
  - '@design-factory/*'

packageExtensions:
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": ^8.15.0
  nx@*:
    dependencies:
      "@swc/core": ~1.13.0
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0
      "ioredis": ^5.3.2

yarnPath: .yarn/releases/yarn-4.10.3.cjs

logFilters:
    # Filter of logs for jest and jest-environment-jsdom which don't satisfy what @angular-devkit/build-angular requests
    # TODO: remove this filter once @angular-devkit/build-angular updates to jest v30
    # see https://github.com/angular/angular-cli/issues/30760
  - pattern: (jest|jest-environment-jsdom) is listed by your project with version 30*, which doesn't satisfy what @angular-devkit/build-angular *
    level: discard
