nodeLinker: pnp

packageExtensions:
  "probot@*":
    dependencies:
      bottleneck: "^2.19.5"
      body-parser: "^1.20.2"
  "@nx/angular@^16.10.0":
    dependencies:
      "@angular-devkit/build-angular": ~16.2.0
      "@angular-devkit/core": ~16.2.0
      "@angular-devkit/schematics": ~16.2.0
      "@angular/compiler": ~16.2.0
      "@angular/compiler-cli": ~16.2.0
      "@schematics/angular": ~16.2.0
      "@types/node": ^17.0.23
      eslint: ^8.42.0
      rxjs: ^7.8.1
      nx: ^16.10.0
      esbuild: ^0.17.5
      typescript: ~5.1.6
  "@nx/cypress@^16.10.0":
    dependencies:
      typescript: ~5.1.6
  "@nx/devkit@*":
    dependencies:
      nx: ^16.10.0
      typescript: ~5.1.6
  "@nx/jest@^16.10.0":
    dependencies:
      nx: ^16.10.0
      typescript: ~5.1.6
  "@nx/js@^16.10.0":
    dependencies:
      nx: ^16.10.0
      typescript: ~5.1.6
      "@types/node": "^18.0.0"
  "@nx/linter@^16.10.0":
    dependencies:
      nx: ^16.10.0
  "@nx/webpack@^16.10.0":
    dependencies:
      "@types/node": ^17.0.23
      nx: ^16.10.0
      typescript: ~5.1.6
  "@nx/eslint-plugin@^16.10.0":
    dependencies:
      "@typescript-eslint/parser": "^5.60.1"
      eslint: ^8.42.0
  "@storybook/core-common@*":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "@storybook/docs-tools@*":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "postcss-loader@^7.2.4":
    dependencies:
      "@types/node": ^17.0.23

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
