compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: pnp

packageExtensions:
  "@swc-node/register@^1.9.0":
    dependencies:
      "@swc/types": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": ^8.15.0
  nx@*:
    dependencies:
      "@swc/core": ~1.12.0
  probot@*:
    peerDependencies:
      "@types/express-serve-static-core": ^5.0.0

yarnPath: .yarn/releases/yarn-4.9.2.cjs

logFilters:
    # Filter of logs for jest and jest-environment-jsdom which don't satisfy what @angular-devkit/build-angular requests
    # TODO: remove this filter once @angular-devkit/build-angular updates to jest v30
  - pattern: (jest|jest-environment-jsdom) is listed by your project with version 30*, which doesn't satisfy what @angular-devkit/build-angular *
    level: discard
    # Filter of logs for jest, @jest/transform, and @jest/types which don't satisfy what ts-jest requests
    # TODO: remove this filter once ts-jest updates to jest v30
  - pattern: (jest|\@jest\/*) is listed by your project with version 30*, which doesn't satisfy what ts-jest *
    level: discard
