compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@design-factory/design-factory@*":
    peerDependencies:
      "@angular/router": ^17.0.0
  "@nx/angular@^17.1.1":
    dependencies:
      "@angular-devkit/build-angular": ^17.0.0
      "@angular-devkit/core": ^17.0.0
      "@angular-devkit/schematics": ^17.0.0
      "@angular/compiler": ^17.0.0
      "@angular/compiler-cli": ^17.0.0
      "@schematics/angular": ^17.0.0
      "@types/node": ^17.0.23
      esbuild: ^0.17.5
      eslint: ^8.42.0
      nx: ^17.1.1
      rxjs: ^7.8.1
      typescript: ~5.2.2
  "@nx/cypress@^17.1.1":
    dependencies:
      typescript: ~5.2.2
  "@nx/devkit@*":
    dependencies:
      nx: ^17.1.1
      typescript: ~5.2.2
  "@nx/eslint-plugin@^17.1.1":
    dependencies:
      "@typescript-eslint/parser": ^6.11.0
      eslint: ^8.42.0
  "@nx/eslint@^17.1.1":
    dependencies:
      nx: ^17.1.1
  "@nx/jest@^17.1.1":
    dependencies:
      nx: ^17.1.1
      typescript: ~5.2.2
  "@nx/js@^17.1.1":
    dependencies:
      "@types/node": ^18.0.0
      nx: ^17.1.1
      typescript: ~5.2.2
  "@nx/webpack@^17.1.1":
    dependencies:
      "@types/node": ^17.0.23
      nx: ^17.1.1
      typescript: ~5.2.2
  postcss-loader@^7.2.4:
    dependencies:
      "@types/node": ^17.0.23
  probot@*:
    dependencies:
      body-parser: ^1.20.2
      bottleneck: ^2.19.5

yarnPath: .yarn/releases/yarn-4.0.2.cjs
