compressionLevel: mixed

enableScripts: false

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@design-factory/design-factory@*":
    peerDependencies:
      "@angular/router": ~17.1.2
  "@nx/angular@^17.1.1":
    dependencies:
      "@angular-devkit/build-angular": ~17.1.2
      "@angular-devkit/core": ~17.1.2
      "@angular-devkit/schematics": ~17.1.2
      "@angular/compiler": ~17.1.2
      "@angular/compiler-cli": ~17.1.2
      "@schematics/angular": ~17.1.2
      "@types/node": ^20.0.0
      esbuild: ~0.20.0
      eslint: ^8.42.0
      nx: ~17.3.0
      rxjs: ^7.8.1
      typescript: ~5.2.2
  "@nx/cypress@^17.1.1":
    dependencies:
      typescript: ~5.2.2
  "@nx/devkit@*":
    dependencies:
      nx: ~17.3.0
      typescript: ~5.2.2
  "@nx/eslint-plugin@^17.1.1":
    dependencies:
      "@typescript-eslint/parser": ^6.11.0
      eslint: ^8.42.0
  "@nx/eslint@^17.1.1":
    dependencies:
      nx: ~17.3.0
  "@nx/jest@^17.1.1":
    dependencies:
      nx: ~17.3.0
      typescript: ~5.2.2
  "@nx/js@^17.1.1":
    dependencies:
      "@types/node": ^20.0.0
      nx: ~17.3.0
      typescript: ~5.2.2
  "@nx/webpack@^17.1.1":
    dependencies:
      "@types/node": ^20.0.0
      nx: ~17.3.0
      typescript: ~5.2.2
  postcss-loader@^7.2.4:
    dependencies:
      "@types/node": ^20.0.0
  probot@*:
    dependencies:
      body-parser: ^1.20.2
      bottleneck: ^2.19.5

yarnPath: .yarn/releases/yarn-4.1.0.cjs
