import {
  existsSync,
  promises as fs,
} from 'node:fs';
import {
  basename,
  dirname,
  resolve,
} from 'node:path';
import {
  DEFAULT_MANIFEST_FILENAMES,
  OPENAPI_NPM_KEYWORDS,
  // eslint-disable-next-line import/no-unresolved -- Cannot resolve mjs file in current setup (see #3738)
} from '@ama-openapi/core';
import {
  renderFile,
} from 'ejs';
import {
  sync,
} from 'globby';

/**
 * Options for template generation
 */
export interface CreateOptions {
  /** Target directory */
  target: string;
  /** Path to external models */
  externalModelPath: string;
  /** Version of the generator */
  version: string;
  /** Name of the package/artifact */
  packageName: string;
  /** Logger */
  logger: typeof console;
}

const TEMPLATE_EXTENSION = '.template';
const GIT_IGNORE_IO_URL = 'https://www.toptal.com/developers/gitignore/api/node';

/**
 * Retrieve the gitignore content generated by gitignore.io
 * @param options
 */
const getGitIgnoreContent = async (options: CreateOptions) => {
  let standardGitignoreNode = '';
  try {
    const gitignoreResponse = await fetch(GIT_IGNORE_IO_URL);
    if (!gitignoreResponse.ok) {
      throw new Error(`Non-OK response to ${GIT_IGNORE_IO_URL}`);
    }
    standardGitignoreNode = await gitignoreResponse.text();
  } catch (e) {
    options.logger.warn('gitignore.io service are not available, a default minimal gitignore will be generated');
    options.logger.debug(e);
  }
  return standardGitignoreNode;
};

/**
 * Generate Template files
 * @param options
 */
export const generateTemplate = async (options: CreateOptions) => {
  const { generatorDependencies, engines } = JSON.parse(
    await fs.readFile(resolve(__dirname, '..', 'package.json'), { encoding: 'utf8' })
  ) as { generatorDependencies: Record<string, string>; engines: Record<string, string> };
  const templatesDirectory = resolve(__dirname, '..', 'templates');
  const regExpExtension = new RegExp(`\\${TEMPLATE_EXTENSION}$`);
  const exportedFiles: string[] = [
    'bundle',
    'models',
    ...DEFAULT_MANIFEST_FILENAMES
  ];
  const generatedCode = sync('**/*', { cwd: templatesDirectory, dot: true })
    .map(async (templatePath) => {
      const templatePathAbsolute = resolve(templatesDirectory, templatePath);
      const content = await renderFile(
        templatePathAbsolute,
        {
          ...options,
          packageKeywords: OPENAPI_NPM_KEYWORDS,
          nodeSupportedRange: engines.node,
          projectFolder: basename(options.target),
          exportedFiles,
          redoclyVersion: generatorDependencies['@redocly/openapi-core'],
          standardGitignoreNode: await getGitIgnoreContent(options)
        },
        { async: true }
      );
      return {
        templatePath,
        content
      };
    })
    .map(async (file) => {
      const { templatePath, content } = await file;
      const outputPath = resolve(options.target, templatePath.replace(regExpExtension, ''));
      const outputDirectory = dirname(outputPath);
      if (!existsSync(outputDirectory)) {
        await fs.mkdir(dirname(outputPath), { recursive: true });
      }
      await fs.writeFile(outputPath, content, { encoding: 'utf8' });
    });

  return Promise.all(generatedCode);
};
