name: Setup and Install
description: Sets up Node.js and installs dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24<% if (packageManager !== 'yarn') { %>
        cache: <%= packageManager %><% } %>
    - name: Enable Corepack
      shell: bash
      run: corepack enable<% if (packageManager === 'yarn') { %>
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(<% if (yarn2) { %>yarn config get cacheFolder<% } else { %>yarn cache dir<% } %>)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          <% if (yarn2) { %>.yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs<% } %>
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn
          ${{ runner.os }}<% } %>
    - name: Install<% if (npmRegistry) { %>
      env:
        COREPACK_NPM_REGISTRY: <%= npmRegistry %>
        COREPACK_INTEGRITY_KEYS: ""<% } %>
      shell: bash
      run: <%= setupCommand %>
