name: Setup and Install
description: Sets up Node.js and installs dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24<% if (packageManager !== 'yarn') { %>
        cache: <%= packageManager %><% } %>
    - name: Enable Corepack
      shell: bash
      run: corepack enable<% if (packageManager === 'yarn') { %>
    - name: Get yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "dir=$(<% if (yarn2) { %>yarn config get cacheFolder<% } else { %>yarn cache dir<% } %>)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          <% if (yarn2) { %>.yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs<% } %>
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn
          ${{ runner.os }}<% } %>
    - name: Install<% if (npmRegistry) { %>
      env:
        COREPACK_NPM_REGISTRY: <%= npmRegistry %>
        COREPACK_INTEGRITY_KEYS: ""<% } %>
      shell: bash
      run: <%= setupCommand %>
