swagger: '2.0'
info:
  version: 0.0.0
  title: <%= name %> Additional products
  description: >-
    TODO: Add description
tags:
  - name: <%= name %>
    description: <%= name %> Specific routes
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /<%= name %>/example:
    get:
      description: Example of GET request
      operationId: <%= name %>RequestExample
      responses:
        '200':
          description: OK
          schema:
            $ref: '../definitions/<%= name %>ExampleReply.yaml#/definitions/<%= name %>ExampleReply'
      tags:
        - <%= name %>
