name: Upload Build Output
description: Upload a github artifact containing all `dist` outputs
inputs:
  artifactName:
    description: Name of the artifact on which the outputs are published
    default: dist
    required: false

runs:
  using: 'composite'
  steps:
    - run: zip -q -r ${{ inputs.artifactName }}.zip . -i "apps/*/dist/*" "packages/*/dist/*" -x "*/node_modules/*" ".cache/*"
      shell: bash
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: ${{ inputs.artifactName }}
        path: ${{ inputs.artifactName }}.zip
    - run: rm -f ${{ inputs.artifactName }}.zip
      shell: bash
