name: Upload Build Output
description: Upload a github artifact containing all `dist` outputs
inputs:
  artifactName:
    description: Name of the artifact on which the outputs are published
    default: dist
    required: false

runs:
  using: 'composite'
  steps:
    - run: zip -q -r ${{ inputs.artifactName }}.zip . -i "apps/*/dist/*" "packages/*/dist/*" -x "*/node_modules/*" ".cache/*"
      shell: bash
    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: ${{ inputs.artifactName }}
        path: ${{ inputs.artifactName }}.zip
    - run: rm -f ${{ inputs.artifactName }}.zip
      shell: bash
