name: Create branch e2e screenshots
description: Create a branch with the update of the e2e screenshots
inputs:
  screenshotsPattern:
    type: string
    description: 'Pattern to detect which screenshots should be committed'
    required: true
  commitMessage:
    type: string
    description: 'Commit message for the update of the e2e screenshots'
    required: false
    default: 'fix: update e2e screenshots'
  branchName:
    type: string
    description: 'Suffix for the branch that will be created'
    required: false
    default: refs/heads/${{ github.head_ref }}-update-e2e-screenshots

runs:
  using: 'composite'
  steps:
    - name: Create branch
      id: auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
      with:
        commit_message: ${{ inputs.commitMessage }}
        branch: ${{ inputs.branchName }}
        file_pattern: ${{ inputs.screenshotsPattern }}
    - name: Comment the PR
      if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
      env:
        BRANCH_NAME: ${{ inputs.branchName }}
        BRANCH_URL: https://github.com/${{ github.repository }}/tree/${{ inputs.branchName }}
        COMMIT_HASH: ${{ steps.auto-commit-action.outputs.commit_hash }}
        COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ steps.auto-commit-action.outputs.commit_hash }}
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const comment = [
            `[${process.env.BRANCH_NAME}](${process.env.BRANCH_URL}) with the updated screenshots has been created!`,
            `[${process.env.COMMIT_HASH.substring(0, 7)}](${process.env.COMMIT_URL}) can be cherry-picked in your branch.`,
          ].join('\n');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
