import type { PackageJson, TsConfigJson } from 'type-fest';
import type { NgGenerateModuleSchema } from '../schema';
import { findConfigFileRelativePath } from '@o3r/schematics';
import { apply, chain, externalSchematic, MergeStrategy, mergeWith, move, renameTemplateFiles, Rule, template, url } from '@angular-devkit/schematics';
import * as path from 'node:path';
import { readFileSync } from 'node:fs';

/**
 * generate the rules to adapt the library generated by ng cli
 *
 * @param options
 * @param rootPath
 */
export function ngGenerateModule(options: NgGenerateModuleSchema & { targetPath: string}): Rule {
  /**
   * Update Ng templates
   *
   * @param tree File tree
   * @param context Context of the schematics
   */
  const updateNgTemplate: Rule = (tree, context) => {
    const o3rCorePackageJsonPath = path.resolve(__dirname, '..', '..', 'package.json');
    const o3rCorePackageJson: PackageJson & { generatorDependencies?: Record<string, string> } = JSON.parse(readFileSync(o3rCorePackageJsonPath)!.toString());
    const otterVersion = o3rCorePackageJson.dependencies!['@o3r/schematics'];

    const templateNg = apply(url('./templates/ng'), [
      template({
        ...options,
        runner: process.env.npm_execpath && /[\\/][^\\/]yarn[^\\/]js$/.test(process.env.npm_execpath) ? 'yarn run' : 'npm run',
        tsconfigSpecPath: findConfigFileRelativePath(tree,
          ['tsconfig.test.json', 'tsconfig.spec.json', 'tsconfig.jest.json', 'tsconfig.jasmine.json', 'tsconfig.base.json', 'tsconfig.json'], options.targetPath),
        tsconfigBasePath: findConfigFileRelativePath(tree, ['tsconfig.base.json', 'tsconfig.json'], options.targetPath),
        tsconfigBuildPath: findConfigFileRelativePath(tree, ['tsconfig.build.json', 'tsconfig.base.json', 'tsconfig.json'], options.targetPath),
        eslintRcPath: findConfigFileRelativePath(tree, ['.eslintrc.json', '.eslintrc.js'], options.targetPath)
      }),
      renameTemplateFiles(),
      move(options.targetPath)
    ]);

    return chain([
      mergeWith(templateNg, MergeStrategy.Overwrite),
      (t, _c) => {
        /* eslint-disable @typescript-eslint/naming-convention */
        const packageJson = tree.readJson(path.posix.join(options.targetPath, 'package.json')) as PackageJson;
        const runner = process.env.npm_execpath && /[\\/][^\\/]yarn[^\\/]js$/.test(process.env.npm_execpath) ? 'yarn run' : 'npm run';
        packageJson.description = options.description || packageJson.description;
        packageJson.scripts ||= {};
        packageJson.scripts.build = `${runner} build ${options.projectName}`;
        packageJson.scripts['prepare:build:builders'] = `${runner} cpy 'collection.json' dist && ${runner} cpy 'schematics/**/*.json' dist/schematics`;
        packageJson.scripts['build:builders'] = 'tsc -b tsconfig.builders.json --pretty';
        packageJson.peerDependencies ||= {};
        packageJson.peerDependencies['@o3r/dev-tools'] = otterVersion;
        packageJson.peerDependencies['@o3r/schematics'] = otterVersion;
        packageJson.devDependencies ||= {};
        packageJson.keywords ||= [];
        packageJson.keywords.push('otter-module');
        packageJson.version = '0.0.0-placeholder';

        packageJson.devDependencies = {
          ...packageJson.devDependencies,
          '@angular-devkit/build-angular': o3rCorePackageJson.peerDependencies!['@angular-devkit/core'],
          '@angular-devkit/core': o3rCorePackageJson.peerDependencies!['@angular-devkit/core'],
          '@angular-eslint/eslint-plugin': o3rCorePackageJson.generatorDependencies!['@angular-eslint/eslint-plugin'],
          '@angular/cli': packageJson.peerDependencies['@angular/common'],
          '@angular/common': packageJson.peerDependencies['@angular/common'],
          '@angular/compiler': packageJson.peerDependencies['@angular/common'],
          '@angular/compiler-cli': packageJson.peerDependencies['@angular/common'],
          '@angular/core': packageJson.peerDependencies['@angular/common'],
          '@angular/platform-browser': packageJson.peerDependencies['@angular/common'],
          '@angular/platform-browser-dynamic': packageJson.peerDependencies['@angular/common'],
          '@o3r/dev-tools': otterVersion,
          '@o3r/eslint-plugin': otterVersion,
          '@schematics/angular': o3rCorePackageJson.peerDependencies!['@angular-devkit/core'],
          '@types/jest': o3rCorePackageJson.generatorDependencies!.jest,
          '@typescript-eslint/eslint-plugin': o3rCorePackageJson.generatorDependencies!['@typescript-eslint/parser'],
          '@typescript-eslint/parser': o3rCorePackageJson.generatorDependencies!['@typescript-eslint/parser'],
          'cpy-cli': o3rCorePackageJson.generatorDependencies!['cpy-cli'],
          'eslint': o3rCorePackageJson.generatorDependencies!.eslint,
          'eslint-import-resolver-node': o3rCorePackageJson.generatorDependencies!['eslint-import-resolver-node'],
          'eslint-plugin-jest': o3rCorePackageJson.generatorDependencies!['eslint-plugin-jest'],
          'eslint-plugin-jsdoc': o3rCorePackageJson.generatorDependencies!['eslint-plugin-jsdoc'],
          'eslint-plugin-prefer-arrow': o3rCorePackageJson.generatorDependencies!['eslint-plugin-prefer-arrow'],
          'eslint-plugin-unicorn': o3rCorePackageJson.generatorDependencies!['eslint-plugin-unicorn'],
          'jest': o3rCorePackageJson.generatorDependencies!.jest,
          'jest-environment-jsdom': o3rCorePackageJson.generatorDependencies!.jest,
          'jest-junit': o3rCorePackageJson.generatorDependencies!['jest-junit'],
          'jest-preset-angular': o3rCorePackageJson.generatorDependencies!['jest-preset-angular'],
          'rxjs': o3rCorePackageJson.peerDependencies!.rxjs,
          'typescript': o3rCorePackageJson.peerDependencies!.typescript,
          'zone.js': o3rCorePackageJson.generatorDependencies!['zone.js']
        };
        /* eslint-enable @typescript-eslint/naming-convention */
        t.overwrite(path.posix.join(options.targetPath, 'package.json'), JSON.stringify(packageJson, null, 2));
        return t;
      },
      (t, _c) => {
        const ngPackagr = tree.readJson(path.posix.join(options.targetPath, 'ng-package.json')) as any;
        ngPackagr.$schema = 'https://raw.githubusercontent.com/ng-packagr/ng-packagr/master/src/ng-package.schema.json';
        t.overwrite(path.posix.join(options.targetPath, 'ng-package.json'), JSON.stringify(ngPackagr, null, 2));
        return t;
      }
    ])(tree, context);
  };

  /**
   * Update the root tsconfig files mappings
   *
   * @param tree File tree
   * @param context Context of the schematics
   */
  const updateTsonfigFiles: Rule = (tree, context) => {
    const tsconfigBase = findConfigFileRelativePath(tree, ['tsconfig.base.json', 'tsconfig.json'], '/');
    const tsconfigBuild = findConfigFileRelativePath(tree, ['tsconfig.build.json'], '/');
    if (tsconfigBase) {
      const configFile = tree.readJson(tsconfigBase) as TsConfigJson;
      if (configFile?.compilerOptions?.paths) {
        configFile.compilerOptions.paths[options.name] = [path.posix.join(options.path, options.name, 'src', 'public_api')];
        tree.overwrite(tsconfigBase, JSON.stringify(configFile, null, 2));
      } else {
        context.logger.warn(`${tsconfigBase} does not contain path mapping, the edition will be skipped`);
      }
    } else {
      context.logger.warn('No base TsConfig file found');
    }

    if (tsconfigBuild) {
      const configFile = tree.readJson(tsconfigBuild) as TsConfigJson;
      if (configFile?.compilerOptions?.paths) {
        configFile.compilerOptions.paths[options.name] = [
          path.posix.join(options.path, options.name, 'dist'),
          path.posix.join(options.path, options.name, 'src', 'public_api')
        ];
        tree.overwrite(tsconfigBuild, JSON.stringify(configFile, null, 2));
      } else {
        context.logger.warn(`${tsconfigBuild} does not contain path mapping, the edition will be skipped`);
      }
    }
  };

  const ngCliUpdate: Rule = (tree, context) => {
    return chain([
      (t, c) => externalSchematic('@schematics/angular', 'library', {
        name: options.name,
        projectRoot: options.targetPath,
        buildable: true,
        prefix: options.prefix || undefined
      })(t, c),
      updateNgTemplate,
      updateTsonfigFiles
    ])(tree, context);
  };

  return ngCliUpdate;
}
