name: Bug Report to an Application from the Otter project
description: File a bug report on an Application from the Otter project
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure we have all the information we need to investigate efficiently.
  - type: dropdown
    id: app-name
    attributes:
      label: Application name
      description: Which application(s) are you facing issue with?
      multiple: true
      options: [
          Showcase,
          Chrome Devtools,
          VsCode Extension,
          IntelliJ extension,
          Cascading bot
      ]
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. 8.0.1
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Reproduction steps (please include the application URL when possible)
    validations:
      required: true
  - type: textarea
    id: current-result
    attributes:
      label: Current result
      description: What result did you get?
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional comments
      description: Share with us any additional information which could help us in the investigation
    validations:
      required: false
