#
# This is the default configuration file. As it allows all users to do anything,
# please read carefully the documentation and best practices to improve security.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/blob/5.x/conf/docker.yaml
#
# Read about the best practices
# https://verdaccio.org/docs/best

storage: ../storage

plugins: ../plugins

web:
  title: Verdaccio

auth:
  htpasswd:
    file: ../storage/htpasswd
    algorithm: bcrypt

packages:
  '@o3r-training/*':
    access: $all
    publish: $authenticated
    proxy: no-proxy
  '@o3r/*':
    access: $all
    publish: $authenticated
    proxy: no-proxy
  '@ama-sdk/*':
    access: $all
    publish: $authenticated
    proxy: no-proxy
  '@ama-terasu/*':
    access: $all
    publish: $authenticated
    proxy: no-proxy

no_proxy: localhost,127.0.0.1

server:
  keepAliveTimeout: 60

max_body_size: 100mb

middlewares:
  audit:
    enabled: true
