name: 'Setup Java'
description: 'JAVA Setup for Otter Library'

inputs:
  install-jdk:
    description: 'Option to install java'
    required: false
    default: 'false'
  mvn-version:
    description: 'Mvn version to install'
    required: false
    default: '3.8.7'

runs:
  using: "composite"
  steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: ${{ inputs.mvn-version }}
    - name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      if: inputs.install-jdk == 'true'
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
