name: 'Notify parent flow'
description: 'Update triggering workflow with the publish result'
inputs:
  publish-result:
    description: 'publish result'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Update triggering workflow
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        PUBLISH_RESULT: ${{ inputs.publish-result }}
      with:
        script: |
          const backUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/attempts/${context.runAttempt || 1}`;
          await github.rest.checks.create({
              ...context.repo,
              head_sha: context.payload.workflow_run.head_commit.id,
              name: 'publish-specs',
              conclusion: process.env.PUBLISH_RESULT,
              status: 'completed',
              output: {
                title: 'publish-specs',
                summary: `${process.env.PUBLISH_RESULT} publish [${backUrl}](${backUrl})`
              }
          });
