nodeLinker: pnp

npmRegistries:
  //pkgs.dev.azure.com/AmadeusDigitalAirline/DES-SDKs/_packaging/des-sdks/npm/registry/:
    npmAlwaysAuth: true
    npmAuthIdent: REVTLVNES3M6cW40bnducWFobjV6bnh5eXNrZ2tzYWM1eGJ1Z21xeXd5MnB6a203Z2p3aWhvd21saDZuYQ==
  //pkgs.dev.azure.com/AmadeusDigitalAirline/Otter/_packaging/otter/npm/registry/:
    npmAlwaysAuth: true
    npmAuthIdent: REVTLVNES3M6cW40bnducWFobjV6bnh5eXNrZ2tzYWM1eGJ1Z21xeXd5MnB6a203Z2p3aWhvd21saDZuYQ==

npmScopes:
  dapi:
    npmRegistryServer: "https://pkgs.dev.azure.com/AmadeusDigitalAirline/DES-SDKs/_packaging/des-sdks/npm/registry/"
  otter:
    npmRegistryServer: "https://pkgs.dev.azure.com/AmadeusDigitalAirline/Otter/_packaging/otter/npm/registry/"

packageExtensions:
  "@ama-sdk/generator-sdk@*":
    dependencies:
      isomorphic-fetch: ~2.2.1
