name: 'Audit'
description: 'Step to execute yarn audit and add comment in pull request'

inputs:
  severity:
    description: 'Minimal severity requested for packages to be displayed'
    required: false
    default: critical
  allWorkspaces:
    description: 'Audit dependencies from all workspaces'
    required: false
    default: 'true'
  recursive:
    description: 'Audit transitive dependencies as well'
    required: false
    default: 'true'
  environment:
    description: 'Which environments to cover'
    required: false
    default: production
outputs:
  reportJSON:
    description: 'The report in JSON format'
    value: ${{ steps.audit.outputs.reportJSON }}
  reportMarkdown:
    description: 'The report in MarkDown format'
    value: ${{ steps.audit.outputs.reportMarkdown }}
runs:
  using: 'composite'
  steps:
    - id: audit
      run: 'yarn node .github/actions/audit/yarn-audit.mjs'
      shell: bash
      env:
        INPUT_SEVERITY: ${{ inputs.severity }}
        INPUT_ALLWORKSPACES: ${{ inputs.allWorkspaces }}
        INPUT_RECURSIVE: ${{ inputs.recursive }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
