name: 'Setup'
description: 'Setup for Otter Library'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 22
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Cache dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cache/ms-playwright
          .yarn/cache
          .yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Install
      shell: bash
      run: yarn install
