name: 'Setup'
description: 'Setup for Otter Library'

inputs:
  working-directory:
    description: Working directory
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20
    - name: Enable Corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: corepack enable
    - name: Cache dependencies
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: |
          ~/.cache/ms-playwright
          ${{ inputs.working-directory }}/.yarn/cache
          ${{ inputs.working-directory }}/.yarn/unplugged
          ${{ inputs.working-directory }}/.pnp.cjs
          ${{ inputs.working-directory }}/.pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn install
