name: 'Setup'
description: 'Setup for Otter Library'
inputs:
  npm-version:
    description: 'NPM version to install (only if you want a specific version)'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Set NPM version
      if: ${{ inputs.npm-version }}
      shell: bash
      run: npm install -g npm@${{ inputs.npm-version }}
    - name: Cache dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/ms-playwright
          ~/.cache/node-compile-cache
          .yarn/cache
          .yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Install
      shell: bash
      run: yarn install
