name: 'Setup'
description: 'Setup for Otter Library'
inputs:
  npm-version:
    description: 'NPM version to install (only if you want a specific version)'
    required: false
    default: '>=11.6.3'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Set NPM version
      if: ${{ inputs.npm-version }}
      shell: bash
      run: npm install -g npm@${{ inputs.npm-version }}
    - name: Cache dependencies
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: |
          ~/.cache/ms-playwright
          ~/.cache/node-compile-cache
          .yarn/cache
          .yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Install
      shell: bash
      run: yarn install
