name: 'Setup'
description: 'Setup for Otter Library'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Cache dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/.cache/node-compile-cache
          .yarn/cache
          .yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Install
      shell: bash
      run: yarn install
