name: IT Tests report

on:
  workflow_run:
    workflows: ['Main CI']
    types:
      - completed

jobs:
  publish-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest']
        packageManager: ['yarn', 'npm']
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: it-reports-${{ matrix.packageManager }}-${{ matrix.os }}
          name: IT Tests report (run with ${{ matrix.packageManager }} on ${{ matrix.os }})
          path: '**/*.xml'
          reporter: jest-junit
