name: Publish Showcase Specs

on:
  workflow_run:
    workflows: ['Main CI']
    types:
      - completed

permissions:
  contents: read

jobs:
  version:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' && github.event_name != 'merge_group' }}
    permissions:
      actions: read
    runs-on: ubuntu-latest
    outputs:
      nextVersionTag: ${{ steps.newVersion.outputs.nextVersionTag }}
      isPreRelease: ${{ contains( steps.newVersion.outputs.nextVersionTag, '-' ) || github.event_name == 'merge_group'}}

    steps:
      - id: newVersion
        uses: ./.github/actions/get-version-from-logs

  publish-specs:
    runs-on: ubuntu-latest
    needs: [version]
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    environment: production
    secrets: inherit
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 2
      - uses: ./tools/github-actions/download-build-output
      - uses: ./tools/github-actions/setup
      - run: yarn set:version ${{ needs.version.outputs.nextVersionTag }}
      - name: Get tag name
        id: get-npm-tag
        uses: ./tools/github-actions/get-npm-tag
        with:
          is-prerelease: ${{ needs.version.outputs.isPrerelease }}
          version: ${{ needs.version.outputs.nextVersionTag }}
      - name: Publish
        run: yarn nx run ama-sdk-showcase-sdk:publish-specs --tag=${{ steps.get-npm-tag.outputs.tag }} --userconfig=./.npmrc.specs --always-auth=true
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AZURE_AUTH_TOKEN: ${{ secrets.AZURE_AUTH_TOKEN }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}

  notify-parent:
    runs-on: ubuntu-latest
    needs: [publish-specs]
    if: success() || failure()
    permissions:
      # Needed to notify the parent workflow
      checks: write
    steps:
      - uses: ./.github/actions/notify-parent-flow
        with:
          publish-result: ${{ needs.publish-specs.result }}
